
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DBContextLibrary
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectManagerDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProjectManagerDetail()
    {

        this.MasterDataTables = new HashSet<MasterDataTable>();

    }


    public string ID { get; set; }

    public string NAME { get; set; }

    public string CostCentre { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MasterDataTable> MasterDataTables { get; set; }

}

}
