//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JDCTSDBEntities : DbContext
    {
        public JDCTSDBEntities()
            : base("name=JDCTSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MasterDataTable> MasterDataTables { get; set; }
        public virtual DbSet<ProjectManagerDetail> ProjectManagerDetails { get; set; }
        public virtual DbSet<AssociateBilingDetail> AssociateBilingDetails { get; set; }
    
        public virtual ObjectResult<SP_FetchData_Result> SP_FetchData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FetchData_Result>("SP_FetchData");
        }
    }
}
