//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDataTable
    {
        public string AssociateID { get; set; }
        public string AssociateName { get; set; }
        public string RacfID { get; set; }
        public string ProjectManager { get; set; }
        public string CostCentre { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PoNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<bool> AssociateStatus { get; set; }
    
        public virtual AssociateBilingDetail AssociateBilingDetail { get; set; }
        public virtual ProjectManagerDetail ProjectManagerDetail { get; set; }
    }
}
